#!/bin/bash

if [ "$#" -lt "1" ]
then
  echo "Usage:   convertWav file.wav"
  exit 1
fi


tempFile="$1.temp.wav"

sndfile-convert -pcm16 "$1" "$tempFile"

sox "$tempFile" -r 22050 -c 1 "$1" avg resample

rm "$tempFile"