#!/bin/bash


getWavInfoPath="/home/jcr13/cpp/DiamondTrust/gameSource/getWavInfo"


if [ "$#" -lt "1" ]
then
  echo "Finds global normalization factor (1/peak) across an "
  echo "entire song directory of loops"
  echo ""
  echo "Usage:   findVolumePeakInSong song_dir_path"
  echo ""
  exit 1
fi



# set input field separator to newline for "find" output that contains
# spaces in file names
IFS="
"



peak="0"


for file in $( find "$1" -name "*.wav" )
do
  thisPeak=`"$getWavInfoPath" peak "$file"`

  if [ $thisPeak -gt $peak ]
  then
	  peak=$thisPeak
  fi
done

# bc truncates, so this is a "safe" normalization factor (won't clip)
floatPeak=$( echo "scale=2; 32767 / $peak" | bc ); 

echo -n "$floatPeak"
